### PR TITLE
Fixed some broken links

### PR DESCRIPTION
**Pull request by najela**
Fixed some broken links reported by [Jenkins](http://jenkins.jquery.com/view/Websites/job/stage.qunitjs.com/lastBuild/console)

@arschmitz We'll need to ignore some links. Apparently, spider attempts to crawl the test links found on the code sniplet here http://stage.qunitjs.com/intro/.  We'll need to ignore the following links

- http://stage.qunitjs.com/2008/01/blah/57/
- http://stage.qunitjs.com/john/

### CODE REVIEW

**Comment by jzaefferer** [comment]
Merged, thanks! I'll leave it to @arschmitz to update the Jenkins job.

**Comment by arschmitz** [comment]
@jzaefferer @najela It seems to me like rather then add these urls to be ignore, we should change the links to either point at real pages ( still seems odd ), or to just change them to be `#`, or `#2008/01/blah/57/` /  `#john` which would seem to make the most sense to me since these are examples and has based links are perfectly valid this would be my personal recommendation, since it seems kinda ironic to have links the are guaranteed to be broken in every context, in examples for a test framework.

**Comment by jzaefferer** [comment]
Changing the links to points at anchors sounds good to me. @najela could you do another PR for that?

**Comment by najela** [comment]
@arschmitz  @jzaefferer  Take a look at https://github.com/jquery/qunitjs.com/pull/99

**Pull request closed without merging**
