### PR TITLE
Fixed url problem in example-index

### PR DESCRIPTION
**Pull request by moore3071**
Example index couldn't be copy and pasted then used due to missing file transfer protocol. It should be good to copy, paste, and go now.

### CODE REVIEW

**Comment by trentmwillis** [comment]
:+1: thanks @moore3071! Any chance you could update the other examples as well? Looks like they have some protocol-relative urls as well.

**Comment by leobalter** [comment]
Good catch. I missed these files on ca0aebd.

**Comment by moore3071** [comment]
@trentmwillis, that should cover all of the examples, but let me know if I missed one.

**Comment by trentmwillis** [comment]
:+1: thanks @moore3071!

**Pull request closed without merging**
