### PR TITLE
Add Tern QUnit

### PR DESCRIPTION
**Pull request by angelozerr**
Add Tern QUnit.

### CODE REVIEW

**Comment by jzaefferer** [comment]
Can you please [sign our CLA](http://contribute.jquery.org/CLA/)? [There's details here as well](http://contribute.jquery.org/CLA/status/?repo=qunitjs.com&sha=10a329951c331192568e5ca59c9468cf2a346871).

**Comment by arthurvr** [comment]
The thing is that the commits only have your first name in your Git config. You'll need to edit it to include your full name. There are details about that on [the page posted earlier](http://contribute.jquery.org/CLA/status/?repo=qunitjs.com&sha=10a329951c331192568e5ca59c9468cf2a346871).

**Comment by arthurvr** [comment]
ping @angelozerr. We can't land anything without a valid CLA signature.

**Comment by angelozerr** [comment]
@arthurvr to be honnest with you, I have never used gitconfig. My  patch was created by github. I have tried to sign my CLA with http://contribute.jquery.org/CLA/ but it seems that it doesn't work. I will study how to customize gitconfig with github.

**Comment by arthurvr** [comment]
@angelozerr Oh. It should be as easy as cloning your fork, checking out the `patch-1` branch, `git commit --amend --author="First Last <email@gmail.com>"` and force pushing the `patch-1` branch.

**Comment by leobalter** [comment]
@angelozerr I can't merge this without a CLA pass. I'll close this PR, but you can reopen or open a new one once it's fixed.

**Pull request closed without merging**
